version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - 6379:6379

  discountdb:
    container_name: discountdb
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=DiscountDB
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@pgadmin.com
      - PGADMIN_DEFAULT_PASSWORD=secret
    restart: always
    ports:
      - 5051:80
    volumes:
      - pgadmin_data:/root/.pgadmin

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:MongoConnectionString=mongodb://catalogdb:27017"
    depends_on:
      - catalogdb
    ports:
      - 8000:80

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basketdb:6379"
      - "GrpcSettings:DiscountUrl=http://discount.grpc"
    depends_on:
      - basketdb
    ports:
      - 8001:80

  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:PGConnectionString=Server=discountdb;Port=5432;Database=DiscountDB;User Id=root;Password=secret;"
    depends_on:
      - discountdb
    ports:
      - 8002:80

  discount.grpc:
    container_name: discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:PGConnectionString=Server=discountdb;Port=5432;Database=DiscountDB;User Id=root;Password=secret;"
    depends_on:
      - discountdb
    ports:
      - 8003:80